### ISSUE TITLE
TVertScrollView update Text PullLoad 

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#10]
How do I change the text?

![Screenshot_20190414-185814](https://user-images.githubusercontent.com/5359931/56100576-76332e00-5ee8-11e9-9c14-35a81f78ff98.png)

![Screenshot_20190414-185722](https://user-images.githubusercontent.com/5359931/56100577-76332e00-5ee8-11e9-9ec7-23b605cc5a61.png)

**Comment by KngStr** [comment]
look at UI.ListView.Header & UI.ListView.Footer

**Comment by marlonnardi** [comment]
Very thanks @KngStr
