### ISSUE TITLE
Hint(Toast) doen't work's (Delphi 10.3.1)

### ISSUE THREAD

**Issue by andrecampestre** [yangyxd/FMXUI#16]
Hint(Toast) work's in your sample, but doesn't work's in my project.

Somebody have's a tip?

Thanks.

**Comment by KngStr** [comment]
Your app runs in windows? If so, add ToastManager to mainform

**Comment by andrecampestre** [comment]
Yes! I did it.

**Comment by KngStr** [comment]
Already add ToastManager? Please upload a tiny demo.

**Comment by andrecampestre** [comment]
Dude! something wrong is happen. I created a new project, and I called my frame, then de Toats works very well. But in my project, the same frame doen't works.

**Comment by KngStr** [comment]
Well, It's difficult for me to test. Try it yourself.

**Comment by andrecampestre** [comment]
I got it!! Thansk.
