### ISSUE TITLE
Get value from Frame after to use FINISH.

### ISSUE THREAD

**Issue by andrecampestre** [yangyxd/FMXUI#18]
I have two frames:
- Frame_1
- Frame_2

In the Frame_1, I did StartFrame(Frame_2). I need to go back to FRAME_1, but I need values from FRAME_2.  
* I used StartFrame(FrameClass: TFrameViewClass; const Title: string; const Data: TValue) to show FRAME_2;

Somebody could to help me?.

**Comment by KngStr** [comment]
Simply, add a callback property to frame2

**Comment by KngStr** [comment]
Look at the new `baseframe` demo in `beta`
