### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by sdokowe** [yangyxd/FMXUI#19]
Is there any particular reason why these shouldn't be localized?

 CutStyleName = '剪切'; //Do not localize
  CopyStyleName = '复制'; //Do not localize
  PasteStyleName = '粘贴'; //Do not localize
  DeleteStyleName = '删除'; //Do not localize
  SelectAllStyleName = '选择全部'; //Do not localize   

![Shot](https://user-images.githubusercontent.com/31492683/64475197-bb017f00-d17f-11e9-9338-fee52817aaa9.png)

As you can see from the image I'm forced to localize them.

**Comment by KngStr** [comment]
As for your image, what you have to change is in UI.Reg.pas

**Comment by sdokowe** [comment]
> As for your image, what you have to change is in UI.Reg.pas

Looks very different when I translate the strings in the Array, other than the obvious strings in English.

**Comment by KngStr** [comment]
![图片](https://user-images.githubusercontent.com/1308555/64476180-574a7680-d1be-11e9-8866-474237a365c8.png)

To change this, 
- first you have to modify `CmdNames: TArray<string>`
- second reinstall the bpl

**Comment by sdokowe** [comment]
Done, Thank you.

**Comment by sdokowe** [comment]
Done. Thank you.
