### ISSUE TITLE
TTextview的htmltext对连续的<b>标签支持不好

### ISSUE THREAD

**Issue by jonahzheng** [yangyxd/FMXUI#24]
比如下面的文本：
`<b>谈到以色列</b> 大家可能首先  <b>会想到安全</b> 问题，<br/>其实这里是值得您放心前往的一个国家。`

第一个b标签就不起作用。

**Comment by jonahzheng** [comment]
另外标签</b>后面如果没有空格，则b标签也不起作用。
比如下面的文本：
<b>谈到以色列</b>大家可能首先

**Comment by KngStr** [comment]
![图片](https://user-images.githubusercontent.com/1308555/92551007-9575ec80-f28f-11ea-89d7-f03644f2d375.png)
实测没问题。你这边什么环境？
我测试beta，win7，x64

**Comment by jonahzheng** [comment]
我回头再确认一下，到时发一个demo

**Comment by jonahzheng** [comment]
bug已经没有了
