### ISSUE TITLE
How to stop the items animation when scrolling the TListViewEx put on a TPopup

### ISSUE THREAD

**Issue by GaNacereddine** [yangyxd/FMXUI#28]
If I put the TListViewEx on a TPopUp and scroll. there is an item animation happening when scrolling (the items slid from the side to their position). 
I would like to stop that and let the items scroll the classic way.

this only happens if I put the list on a TPopup.

**Comment by KngStr** [comment]
I did not see the animation.
Would you upload a simple demo?

**Comment by GaNacereddine** [comment]
![listItemAnime](https://user-images.githubusercontent.com/33737454/93573852-8d086a80-f98f-11ea-9221-267253677dfb.gif)
this is the effect I'm seeing

**Comment by KngStr** [comment]
Did you use `UI.Frame` in the sub frame?
If so, remove it or set the default animate to be none.

**Comment by GaNacereddine** [comment]
Yes that was the solution thank you very much.

I also have some problems showing some SVG images in your TImageView, they are not rendered correctly,
can you tell me what is the proper way to report them and how can I contribute to this repo if I want to fix them.
I mean the list of units I should see if I want to tackle the bugs or lack of features in the SVG parser.

**Comment by KngStr** [comment]
@GaNacereddine 

You are welcome.

The SVG problem seems like Delphi's bug. It draw lines or rectangles not correctly.
If you are intresting to fix it, you should look at `UI.Utils.SVGImage`

**Comment by GaNacereddine** [comment]
Okay thank you very much. I will close the issue now and see what I can do for the parser.
