### ISSUE TITLE
Add Support for ellipsis automatic in TTextView

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#33]
Sample this text:
Editando Despesa Recorrente Referente ao Documento

with ellipsis, sample:
Editando Despesa Recorrente Re ...

![image](https://user-images.githubusercontent.com/5359931/139738664-e1fe2720-3910-4f89-930c-e149b06550c9.png)

![image](https://user-images.githubusercontent.com/5359931/139738856-aaaa6757-88d5-41a4-92dc-d570f09790f3.png)

**Comment by KngStr** [comment]
You can do it in `TestSettings.Trimming`

**Comment by marlonnardi** [comment]
> You can do it in `TestSettings.Trimming`

Perfect, thanksss!!!
