### ISSUE TITLE
Add Support for getting the event when animation completes in TFrameView

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#34]
We currently have the following events:

```
 property OnShow: TNotifyEvent read FOnShow write FOnShow;
 property OnHide: TNotifyEvent read FOnHide write FOnHide;
 property OnFinish: TNotifyEvent read FOnFinish write FOnFinish; 
 property OnReStart: TNotifyEvent read FOnReStart write FOnReStart;
 property OnFree: TNotifyEvent read FOnFree write FOnFree;
```

If possible, add a new event that fires when the frame's animation completes.

**Comment by KngStr** [comment]
You can do this with 

procedure Show(Ani: TFrameAniType; **AOnFinish**: TNotifyEventA);

**Comment by KngStr** [comment]
Can I test with new methods?

**Comment by marlonnardi** [comment]
> Can I test with new methods?

Its very very perfect, no lag, no crashes, extremely fluid as it has to be.
tested in Windows and IOS.

![perfect](https://user-images.githubusercontent.com/5359931/142776955-5746cf4f-52eb-425c-b42d-a57959ecb0cd.gif)

**Comment by KngStr** [comment]
OK. Thanks for testing.
