### ISSUE TITLE
ListViewEx + Headers/Sections + Index

### ISSUE THREAD

**Issue by kazuser** [yangyxd/FMXUI#38]
Could you please add fixed headers/sections and the index list (like in UITableView on iOS)?

![изображение](https://user-images.githubusercontent.com/3335273/142620808-0dfc08fa-356c-427a-bfb5-7f596ae8d74d.png)

**Comment by KngStr** [comment]
You can do this yourself.
Take a look at group listview

**Comment by kazuser** [comment]
👌
