### ISSUE TITLE
SVG?

### ISSUE THREAD

**Issue by kazuser** [yangyxd/FMXUI#44]
Hi!

Trying to load SVG but no success :(

![image](https://user-images.githubusercontent.com/3335273/151742623-c437638f-1af6-4ceb-872c-37ef6fd203a6.png)

Source files: https://www.svgrepo.com/svg/390913/cold-drink + https://www.svgrepo.com/svg/390916/compass

**Comment by kazuser** [comment]
Delphi 11 - the same :(

**Comment by KngStr** [comment]
Sorry. SVG is not recommanded.
