### ISSUE TITLE
Crash app IOS in TTextView -> SVGimage.Parse()

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#46]
Platforms

- Windows = OK
- IOS = ERROR

```delphi
TViewBrushBase(TVSearch.Drawable.ItemDefault).SVGImage.Parse(
      '<svg style="width:24px;height:24px" viewBox="0 0 24 24">'+
      '<path fill="currentColor" d="M15,19.88C15.04,20.18 14.94,20.5 14.71,20.71C14.32,21.1 13.69,21.1 13.3,20.71L9.29,16.7C9.06,16.47 '+
      '8.96,16.16 9,15.87V10.75L4.21,4.62C3.87,4.19 3.95,3.56 4.38,3.22C4.57,3.08 4.78,3 5,3V3H19V3C19.22,3 19.43,3.08 '+
      '19.62,3.22C20.05,3.56 20.13,4.19 19.79,4.62L15,10.75V19.88M7.04,5L11,10.06V15.58L13,17.58V10.05L16.96,5H7.04Z"/></svg>');
```

![image](https://user-images.githubusercontent.com/5359931/155857675-58fc243f-6b91-4f4a-af48-204307ff5800.png)

Delphi 11
iPhone Xr IOS 15.3.1

**Comment by kazuser** [comment]
Try to replace this:
![image](https://user-images.githubusercontent.com/3335273/157274177-f9a8b932-51f8-4534-9aac-c4022b5d7921.png)

by this: `<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">`

**Comment by kazuser** [comment]
And this:
![image](https://user-images.githubusercontent.com/3335273/157274842-80fb5106-ff22-48f4-8ea8-39c6d08d1dbb.png)

by this: `fill="#333333"` (just test)

**Comment by marlonnardi** [comment]
Thanks @kazuser, I will validate this

**Comment by marlonnardi** [comment]
Solved
