### ISSUE TITLE
Get Value From Target Frame

### ISSUE THREAD

**Issue by yuskamal** [yangyxd/FMXUI#5]
How can I get value from target frame

**Comment by KngStr** [comment]
Try to make your own property

**Comment by stackerliew** [comment]
I made my own property already but still failed with av.

**Comment by KngStr** [comment]
@stackerliew look at the baseframe demo at beta branch

**Comment by KngStr** [comment]
@stackerliew look at the baseframe demo at beta branch

**Comment by stackerliew** [comment]
Where is beta branch?

**Comment by stackerliew** [comment]
Ok, I found it already, thanks.
