### ISSUE TITLE
在使用多选列表适配器时，单击item时会触发两次ItemClick

### ISSUE THREAD

**Issue by moyaoo** [yangyxd/FMXUI#51]
请问在DoCheckChange方法中，这段代码的具体作用：
if Assigned(ListView.FOnItemClick) then
   ListView.FOnItemClick(ListView, TControl(Sender).Tag, TControl(Sender));
注释这段代码后，itemclick事件就正常了。

**Comment by KngStr** [comment]
调用绑定的OnItmeClick的，这里出问题，大概率是你写的OnItmeClick调用出错了

**Comment by moyaoo** [comment]
> 调用绑定的OnItmeClick的，这里出问题，大概率是你写的OnItmeClick调用出错了
DEMO里测试也会出现这现象，但我只测试TStringsListCheckAdapter、TStringsListAdapter适配器，多选适配器会触发两次click事件，普通适配器只触发一次

**Comment by KngStr** [comment]
那得你给出更详细的重现步骤了。目前这点信息，无法判断
