### ISSUE TITLE
TDialogBuilder -> SetItems -> FontSize Items

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#52]
How do I access the FontSize property when adding Items to the List?

![image](https://user-images.githubusercontent.com/5359931/197389762-2f69f460-a4b2-425c-8dd3-62f91561e9f7.png)

![image](https://user-images.githubusercontent.com/5359931/197389801-a2f9e0f2-e306-4c5e-b7a6-a993474ee9f7.png)

![image](https://user-images.githubusercontent.com/5359931/197389930-9044def6-2ae3-4d3d-95e4-8ba50b454aba.png)

**Comment by marlonnardi** [comment]
@KngStr Is there a possibility to implement this?

**Comment by KngStr** [comment]
You can do this by custom adapter

```pascal

{ TCustomStringsListAdapter }

function TCustomStringsListAdapter.GetView(const Index: Integer;
  ConvertView: TViewBase; Parent: TViewGroup): TViewBase;
begin
  Result := inherited GetView(Index, ConvertView, Parent);
  if (ConvertView = nil) or (not (ConvertView is TListTextItem)) then begin
    TListTextItem(Result).Gravity := TLayoutGravity.Center;
    TListTextItem(Result).TextSettings.Font.Size := 30;
  end;
end;
```
Test unit :**FMXUI\demos\standard\uFrameDialog.pas**. `ButtonView20Click`

**Comment by marlonnardi** [comment]
Perfect, it worked, thanks again.
