### ISSUE TITLE
TEditView -> ControlType = Plataform ?

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#53]
Is there a possibility to add support for ControlType in TEditView components?

In the same way that it exists in the native TEdit components?

![image](https://user-images.githubusercontent.com/5359931/199586897-77bc2740-e711-4be4-871c-b9e42187a317.png)

**Comment by KngStr** [comment]
Sorry. No plan for now.

**Comment by marlonnardi** [comment]
> Sorry. No plan for now.

Thank you, I understand about the complexity of this item.
