### ISSUE TITLE
In Delphi 11.3 Animations no longer work in [TFrameAniType]

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#55]
To test open the example project: ..\demos\standard

https://altd.embarcadero.com/download/radstudio/11.0/RADStudio_11_3_esd_28_12819.exe

**Comment by marlonnardi** [comment]
Can you help us @KngStr  @yangyxd ?

This project is very important for my business.

**Comment by KngStr** [comment]
We are working on it.

Now you can try this patch form: 柴头柴脑
![patch1](https://user-images.githubusercontent.com/1308555/232323090-28623a9c-bf8e-44de-a0ef-04253a14ef88.jpg)

![patch2](https://user-images.githubusercontent.com/1308555/232323093-84300f6f-ef5d-4559-a356-127545b9ccd9.jpg)

**Comment by marlonnardi** [comment]
Perfect, thanks!

**Comment by KngStr** [comment]
Thanks for your feedback.
