### ISSUE TITLE
TVertScrollView -> UI.ListView.Header [position of loading]

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#58]
It is not obeying the loading height (Atualizando...).

Delphi 11.2 = OK
![image](https://user-images.githubusercontent.com/5359931/232607914-643fdcf7-8c6b-4dba-a0ad-e82d27e547c9.png)

Delphi 11.3 
![image](https://user-images.githubusercontent.com/5359931/232608082-d97f2b9a-a928-4b20-9164-cc49f6357476.png)

[UI.ListView.Header.zip](https://github.com/yangyxd/FMXUI/files/11255661/UI.ListView.Header.zip)

**Comment by KngStr** [comment]
It can't be reproduced.
We need a demo.

**Comment by marlonnardi** [comment]
I will make a sample project for you.

**Comment by marlonnardi** [comment]
Hi @KngStr did you find any clues?

**Comment by KngStr** [comment]
@marlonnardi I don't have time to do it yet. Maybe this week.

**Comment by KngStr** [comment]
@marlonnardi It should be fixed. Can you have a try?

**Comment by marlonnardi** [comment]
> @marlonnardi It should be fixed. Can you have a try?

Perfect, problem solved, very thx!
