### ISSUE TITLE
Bug TEditView - Password True

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#6]
the component does not behave the way it expects when entered password True.
The same is bugged when the text is deleted.

Delphi 10.3 Version 26.0.32429.4364 
Android 8.0 - Moto g6

**Comment by marlonnardi** [comment]
[SOLVED]
UI.Edit.pas -> Line 549

`{$IFDEF ANDROID}
function PackText(const AText: string): string;
begin
  if not AText.IsEmpty then
  begin
    //Result := Format('[%d]%s', [AText.Length, AText]);
    Result := Format('%s', [AText]);
  end
  else
    Result := string.Empty;
end;
{$ENDIF}`

**Comment by yangyxd** [comment]
You are right. Thank you.
