### ISSUE TITLE
[Delphi 12] [UI.Frame] Fix NativeInt as a Weak Alias

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#62]
![image](https://github.com/yangyxd/FMXUI/assets/5359931/797707df-a564-4111-ac4c-4c43d8cd3418)

https://blog.marcocantu.com/blog/2023-october-nativeint-weak-alias.html

`[dcc32 Error] UI.Frame.pas(68): E2252 Method 'Put' with identical parameters already exists
[dcc32 Error] UI.Frame.pas(89): E2252 Method 'Put' with identical parameters already exists
[dcc32 Error] UI.Frame.pas(139): E2252 Method 'Put' with identical parameters already exists
[dcc32 Error] UI.Frame.pas(1737): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] UI.Frame.pas(1754): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] UI.Frame.pas(2012): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] UI.Frame.pas(2077): E2250 There is no overloaded version of 'Synchronize' that can be called with these arguments
[dcc32 Error] UI.Frame.pas(2317): E2251 Ambiguous overloaded call to 'Put'
  UI.Frame.pas(68): Related method: function TFrameStateDataHelper.Put(const string; const NativeUInt): TFrameStateData;
  UI.Frame.pas(65): Related method: function TFrameStateDataHelper.Put(const string; const Cardinal): TFrameStateData;
[dcc32 Error] UI.Frame.pas(2322): E2251 Ambiguous overloaded call to 'Put'
  UI.Frame.pas(68): Related method: function TFrameStateDataHelper.Put(const string; const NativeUInt): TFrameStateData;
  UI.Frame.pas(65): Related method: function TFrameStateDataHelper.Put(const string; const Cardinal): TFrameStateData;
[dcc32 Error] UI.Frame.pas(2341): E2251 Ambiguous overloaded call to 'Put'
  UI.Frame.pas(68): Related method: function TFrameStateDataHelper.Put(const string; const NativeUInt): TFrameStateData;
  UI.Frame.pas(65): Related method: function TFrameStateDataHelper.Put(const string; const Cardinal): TFrameStateData;
[dcc32 Error] UI.Frame.pas(2360): E2004 Identifier redeclared: 'TFrameState.Put'
[dcc32 Error] UI.Frame.pas(2362): E2251 Ambiguous overloaded call to 'Put'
  UI.Frame.pas(68): Related method: function TFrameStateDataHelper.Put(const string; const NativeUInt): TFrameStateData;
  UI.Frame.pas(65): Related method: function TFrameStateDataHelper.Put(const string; const Cardinal): TFrameStateData;
[dcc32 Error] UI.Frame.pas(2587): E2004 Identifier redeclared: 'TFrameStateDataHelper.Put'
[dcc32 Error] UI.Frame.pas(2717): E2004 Identifier redeclared: 'TFrameParamsHelper.Put'
[dcc32 Error] UI.Frame.pas(65): E2065 Unsatisfied forward or external declaration: 'TFrameStateDataHelper.Put'
[dcc32 Error] UI.Frame.pas(86): E2065 Unsatisfied forward or external declaration: 'TFrameParamsHelper.Put'
[dcc32 Error] UI.Frame.pas(136): E2065 Unsatisfied forward or external declaration: 'TFrameState.Put'
[dcc32 Fatal Error] UI.ListView.Header.pas(42): F2063 Could not compile used unit 'UI.Frame.pas'`

**Comment by marlonnardi** [comment]
Download Rad Studio 12
https://altd.embarcadero.com/download/radstudio/12.0/RADStudio_12_0_esd_4915718.exe

**Comment by KngStr** [comment]
It's fixed. Enjoy
