### ISSUE TITLE
SetDefaultStatusColor Not work in Delphi 10.3

### ISSUE THREAD

**Issue by marlonnardi** [yangyxd/FMXUI#7]
First of all, congratulations on your excellent work.
Coming back to the problem Statubar on Android does not work when set.

Project Demo -> TFrameView.SetDefaultStatusColor($ff800080);

Delphi 10.3 Version 26.0.32429.4364
Android 8.0 - Moto g6

**Comment by KngStr** [comment]
Did you set emb's styles.xml disabled?

**Comment by marlonnardi** [comment]
Solved, very thanks ;)
![Screenshot_20190613-082236](https://user-images.githubusercontent.com/5359931/59432144-9ed68780-8db4-11e9-884f-e8c336fa361d.png)

**Comment by KngStr** [comment]
Well, your app looks very nice.

**Comment by stackerliew** [comment]
> Did you set emb's styles.xml disabled?

How To Set emb's styles.xml disabled?

**Comment by KngStr** [comment]
@stackerliew open deployment, and uncheck the styles.xml

**Comment by stackerliew** [comment]
I use 10.3.2, unchecked all styles.xml, still doesn't work.

**Comment by KngStr** [comment]
ok, I'll check it out
